# Generated by Django 5.2.7 on 2026-03-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TenantRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("db_alias", models.CharField(max_length=100, unique=True)),
                ("db_name", models.CharField(max_length=255)),
                ("db_user", models.CharField(blank=True, default="", max_length=255)),
                (
                    "db_password",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("db_host", models.CharField(blank=True, default="", max_length=255)),
                ("db_port", models.CharField(blank=True, default="", max_length=20)),
                ("db_options", models.JSONField(blank=True, default=dict)),
                ("use_isolated_db", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisioning"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                ("plan", models.CharField(default="starter", max_length=30)),
                ("subdomain", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
