from .base import *  # noqa: F403

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
TENANT_AUTO_REGISTER_DATABASES = True
TENANT_ENFORCE_DB_READY = True
